export const TOGGLE_NAVIGATION = "TOGGLE_NAVIGATION";
export const TOGGLE_SETTING = "TOGGLE_SETTING";
export const SET_DARK_THEME = "SET_DARK_THEME";
export const SET_LIGHT_THEME = "SET_LIGHT_THEME";
export const SET_PRIMARY_COLOR = "SET_PRIMARY_COLOR";
